In [2]:
import gc
import os
import sys

from src import loader, zdF, roi, timesync
import glob
from nre.io import load, save
import numpy as np
import pandas as pd
from tqdm import tqdm, trange
import h5py
import nibabel as nib


In [18]:
for z in range(11):
    print(z)

0
1
2
3
4
5
6
7
8
9
10


In [25]:
base_data_path = '/Volumes/AhmedLab/princess/data/pIP10'
experiments = glob.glob(f'{base_data_path}/processed/*win01*')[0]

basename = os.path.basename(experiments)
print(f'Processing {basename}')
# pull timestamps
raw_path = loader.get_base_path(experiment_id=basename, data_stage='raw', base_dir=base_data_path)
processed_path = loader.get_base_path(experiment_id=basename, data_stage='processed', base_dir=base_data_path)


all_nii = glob.glob(processed_path + '/motion_corrected_*.nii')
# n_volumes = len(all_nii)
n_volumes = 50
print(f'Number of volumes: {n_volumes}')

# try loading in a single slice, clustering and df/f calculations one slice at a time
single_volume = nib.load(all_nii[0], mmap=True)
single_volume_data = np.asarray(single_volume.dataobj[..., 10])



for i in range(n_volumes):
    nii = f'{processed_path}/motion_corrected_volume{i}.nii'
    print(nii)
    n_zpos = 11
    for z in range(n_zpos):
        slice_data = np.empty([512,512, 11])
        loading = nib.load(nii, mmap=True)
        data = np.asarray(loading.dataobj[..., i])
        slice_data[...,i] = data
        print(data.shape)


# print(single_volume_data.shape)
# print(type(single_volume_data))
# print(single_volume_data)


# # initializing array of the final size, then loading in nii and assigning it to the array at that index
#
# brain_array = np.empty([512, 512, 11, n_volumes], dtype=np.float32)
# # print(f'size of empty brain array: {sys.getsizeof(brain_array)/1000000} Mbytes')
# for vol in trange(0, n_volumes):
#     single_nii = glob.glob(f'{processed_path}/motion_corrected_volume{vol}.nii')[0]
#     single_volume = load(single_nii)
#     print(type(single_volume[0,0,0]))
#     print(sys.getsizeof(single_volume))
#     brain_array[..., vol] = single_volume
#     # brain_list.append(single_volume)
#     del single_volume
#     gc.collect()
#     # print(f'size of brain array: {sys.getsizeof(brain_array)/1000000} Mbytes')

# appending to list, then using np.stack to reshape to x,y,z,t

#
# n_clusters = 20~~~~~~~~
# print('extracting clusters')
# cluster_labels = roi.extract_ROIs(brain_array, n_clusters)
# print('calculating zscoredF')
# df = zdF.calculate_zscoredF(
#     brain = brain_array,
#     labels_arr=cluster_labels,
#     n_clusters=n_clusters
# )
# file_name = f'{processed_path}/{n_clusters}_signals.h5'
# hf = h5py.File(file_name, 'w')
# hf.create_dataset('labels', data=cluster_labels)
# hf.create_dataset('df/f', data=df)
# # hf.create_dataset('timestamps', data=scope_timestamps)
# hf.close()
# print(f'Finished extracting {n_clusters} clusters, saved to {file_name}')
#
# del brain_array, cluster_labels, df, hf
# gc.collect()

Processing pIP10_TSeries_20260427_GC8m_fly09_win01_trial-001
Number of volumes: 50
/Volumes/AhmedLab/princess/data/pIP10/processed/pIP10_TSeries_20260427_GC8m_fly09_win01_trial-001/motion_corrected_volume0.nii
0
1
2
3
4
5
6
7
8
9
/Volumes/AhmedLab/princess/data/pIP10/processed/pIP10_TSeries_20260427_GC8m_fly09_win01_trial-001/motion_corrected_volume1.nii
0
1
2
3
4
5
6
7
8
9
/Volumes/AhmedLab/princess/data/pIP10/processed/pIP10_TSeries_20260427_GC8m_fly09_win01_trial-001/motion_corrected_volume2.nii
0
1
2
3
4
5
6
7
8
9
/Volumes/AhmedLab/princess/data/pIP10/processed/pIP10_TSeries_20260427_GC8m_fly09_win01_trial-001/motion_corrected_volume3.nii
0
1
2
3
4
5
6
7
8
9
/Volumes/AhmedLab/princess/data/pIP10/processed/pIP10_TSeries_20260427_GC8m_fly09_win01_trial-001/motion_corrected_volume4.nii
0
1
2
3
4
5
6
7
8
9
/Volumes/AhmedLab/princess/data/pIP10/processed/pIP10_TSeries_20260427_GC8m_fly09_win01_trial-001/motion_corrected_volume5.nii
0
1
2
3
4
5
6
7
8
9
/Volumes/AhmedLab/princess/data/pIP

In [34]:
base_data_path = '/Volumes/AhmedLab/princess/data/pIP10'
# window2_experiments = glob.glob(f'{base_data_path}/processed/*win02 *')
window1_experiments = glob.glob(f'{base_data_path}/processed/*win01*')
# experiments = window2_experiments + window1_experiments
experiments = window1_experiments
print(experiments)

for idx, e in enumerate(experiments):
    print(e)
    if idx == 1:
        break
    # if idx == 1 or idx == 7 or idx == 8:
    #     continue
    basename = os.path.basename(e)
    print(f'Processing {basename}, index: {idx}')
    # pull timestamps
    raw_path = loader.get_base_path(experiment_id=basename, data_stage='raw', base_dir=base_data_path)
    processed_path = e

    # extract_supervoxels_multinii(raw_path, processed_path, n_clusters=20)
    all_nii = glob.glob(processed_path + '/motion_corrected*.nii')
    n_volumes = len(all_nii)
    print(f'Number of volumes: {n_volumes}')
    n_volumes = 16
    print('extracting timestamps')
    # scope_timestamps = timesync.extract_scope_timestamps(raw_path, plot=False)

    # initializing array of the final size, then loading in nii and assigning it to the array at that index

    brain_array = np.zeros([512, 512, 11, n_volumes], dtype=np.float32)
    print(f'size of empty brain array: {sys.getsizeof(brain_array)/1000000} Mbytes')
    for vol in trange(0, n_volumes):
        single_nii = glob.glob(f'{processed_path}/motion_corrected_volume{vol}.nii')[0]
        single_volume = load(single_nii)
        # print(type(single_volume[0,0,0]))
        # print(sys.getsizeof(single_volume))
        brain_array[..., vol] = single_volume
        # brain_list.append(single_volume)
        del single_volume

        # gc.collect()
        print(f'size of brain array: {sys.getsizeof(brain_array)/1000000} Mbytes')

    # appending to list, then using np.stack to reshape to x,y,z,t
    #
    # brain_list = []
    # for vol in trange(0, n_volumes):
    #     single_nii = all_nii[vol]
    #     # single_volume = loader.load_nii(single_nii)
    #     single_volume = load(single_nii)
    #     brain_list.append(single_volume)
    #     del single_volume
    #     gc.collect()
    # print(len(brain_list))
    # print(f'size of brain array: {sys.getsizeof(brain_array)/1000000} Mbytes')
    # brain_array = np.stack(brain_list, axis=-1) # never makes it past this, idk if it's just running for hours to
    # del brain_list
    # print(f'final shape after stitching: {brain_array.shape}')
    # # save(f'{processed_path}/brain_array_stitching_test.nii', brain_array)
    #
    # n_clusters = 20
    # print('extracting clusters')
    # cluster_labels = roi.extract_ROIs(brain_array, n_clusters)
    # print('calculating zscoredF')
    # df = zdF.calculate_zscoredF(
    #     brain = brain_array,
    #     labels_arr=cluster_labels,
    #     n_clusters=n_clusters
    # )
    # file_name = f'{processed_path}/{n_clusters}_signals.h5'
    # hf = h5py.File(file_name, 'w')
    # hf.create_dataset('labels', data=cluster_labels)
    # hf.create_dataset('df/f', data=df)
    # # hf.create_dataset('timestamps', data=scope_timestamps)
    # hf.close()
    # print(f'Finished extracting {n_clusters} clusters, saved to {file_name}')
    #
    # del brain_array, cluster_labels, df, hf
    # gc.collect()

['/Volumes/AhmedLab/princess/data/pIP10/processed/pIP10_TSeries_20260427_GC8m_fly09_win01_trial-001', '/Volumes/AhmedLab/princess/data/pIP10/processed/pIP10_TSeries_20260430_GC8m_fly11_win01_trial-001', '/Volumes/AhmedLab/princess/data/pIP10/processed/pIP10_TSeries_20260430_GC8m_fly11_win01_trial-002']
/Volumes/AhmedLab/princess/data/pIP10/processed/pIP10_TSeries_20260427_GC8m_fly09_win01_trial-001
Processing pIP10_TSeries_20260427_GC8m_fly09_win01_trial-001, index: 0
Number of volumes: 2779
extracting timestamps
size of empty brain array: 184.549536 Mbytes


 31%|███▏      | 5/16 [00:00<00:00, 43.87it/s]

size of brain array: 184.549536 Mbytes
size of brain array: 184.549536 Mbytes
size of brain array: 184.549536 Mbytes
size of brain array: 184.549536 Mbytes
size of brain array: 184.549536 Mbytes
size of brain array: 184.549536 Mbytes
size of brain array: 184.549536 Mbytes


 69%|██████▉   | 11/16 [00:00<00:00, 49.23it/s]

size of brain array: 184.549536 Mbytes
size of brain array: 184.549536 Mbytes
size of brain array: 184.549536 Mbytes
size of brain array: 184.549536 Mbytes


100%|██████████| 16/16 [00:00<00:00, 50.23it/s]

size of brain array: 184.549536 Mbytes
size of brain array: 184.549536 Mbytes
size of brain array: 184.549536 Mbytes
size of brain array: 184.549536 Mbytes
size of brain array: 184.549536 Mbytes
/Volumes/AhmedLab/princess/data/pIP10/processed/pIP10_TSeries_20260430_GC8m_fly11_win01_trial-001


In [15]:
type(brain_array[0,0,0,0])
sys.getsizeof(brain_array)
# print(brain_array[0])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


quick plots for pIP10

In [ ]:
from src import visualizations
import xarray as xr
base_data_path = '/Volumes/AhmedLab/princess/data/pIP10'
experiment_id = 'pIP10_TSeries_20260427_GC8m_fly09_win02_trial-001'
processed_path = loader.get_base_path(experiment_id=experiment_id, data_stage='processed', base_dir=base_data_path)

cluster_labels, signal, timestamps = loader.load_clusters(processed_path)

In [ ]:
type(timestamps)

In [ ]:
signal_xr = xr.DataArray(
    data=signal,
    dims=['zposs', 'roi', 'time'],
    coords={'time': range(signal.shape[2])}
)
dimensions = [512, 512, 11]


In [ ]:
for z in range(10):
    to_plot = [[z, x]for x in range(signal.shape[1])]
    visualizations.plot_zscored_activity(to_plot, signal_xr)
    visualizations.plot_spatial_location(to_plot, cluster_labels, dimensions)